### ISSUE TITLE
interface{} == bool cannot be simplified

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-simple#34] opened 2017-01-05 18:05 UTC
```
package foo

func Foo(v interface{}) {
        if v == true {
        }
}
```

```
 $ gosimple f.go
f.go:4:5: should omit comparison to bool constant, can be simplified to v (S1002)
```

Again, nasty piece of code.

**Comment by dominikh** [comment] 2017-01-06 05:37
Duplicate of #28

**Closed as completed by dominikh** 2017-01-06 05:37 UTC
Labels: duplicate

**Comment by mvdan** [comment] 2017-01-06 11:16
Whoops, didn't notice.
