### ISSUE TITLE
Check S1013 with function calls from other packages

### ISSUE THREAD

**Issue by eikeCL** [dominikh/go-simple#32] opened 2017-01-03 15:09 UTC
When I run gosimple on the following program:

```
package main

import "errors"

func validateBool(isTrue bool) error {
	if !isTrue {
		return errors.New("Expected true. Value is false")
	}
	return nil
}

func validate() error {
	if err := validateBool(false); err != nil {
		return err
	}
	return nil
}

func main() {
	err := validate()
	_ = err
}
```

it prints following suggestion:

```
gosimple
/home/eike/gows/src/sandbox/main.go:16:2: 'if err != nil { return err }; return nil' can be simplified to 'return err'
```

Gosimple will not print the suggestion when I move the validateBool function in a package:

```
package main

import "sandbox/pkg1"

func validate() error {
	if err := pkg1.ValidateBool(false); err != nil {
		return err
	}
	return nil
}

func main() {
	err := validate()
	_ = err
}
```

**Comment by dominikh** [comment] 2017-01-20 06:44
I cannot reproduce your issue:

```
$ cat $GOPATH/src/sandbox/foo/foo.go
package main

import "sandbox/bar"

func validate() error {
	if err := bar.ValidateBool(false); err != nil {
		return err
	}
	return nil
}

func main() {
	err := validate()
	_ = err
}
$ 
$ cat $GOPATH/src/sandbox/bar/bar.go
package bar

import "errors"

func ValidateBool(isTrue bool) error {
	if !isTrue {
		return errors.New("Expected true. Value is false")
	}
	return nil
}
$ 
$ gosimple sandbox/foo
/home/dominikh/prj/src/sandbox/foo/foo.go:6:2: 'if err != nil { return err }; return nil' can be simplified to 'return err' (S1013)
```

Are you using the latest version of gosimple?

**Comment by eikeCL** [comment] 2017-01-20 09:36
```
$ cat $GOPATH/src/sandbox/foo/foo.go
package main

import "sandbox/bar"

func validate() error {
	if err := bar.ValidateBool(false); err != nil {
		return err
	}
	return nil
}

func main() {
	err := validate()
	_ = err
}
$ cat $GOPATH/src/sandbox/bar/bar.go
package bar

import "errors"

func ValidateBool(isTrue bool) error {
	if !isTrue {
		return errors.New("Expected true. Value is false")
	}
	return nil
}
$ gosimple sandbox/foo
$ stat $GOPATH/bin/gosimple
  File: '/home/eike/gows/bin/gosimple'
  Size: 6388550   	Blocks: 12480      IO Block: 4096   regular file
Device: 10303h/66307d	Inode: 21760839    Links: 1
Access: (0775/-rwxrwxr-x)  Uid: ( 1000/    eike)   Gid: ( 1000/    eike)
Access: 2017-01-20 09:12:37.597741416 +0000
Modify: 2017-01-03 14:01:57.094933753 +0000
Change: 2017-01-03 14:01:57.106933557 +0000
 Birth: -
$ go get -u honnef.co/go/simple/cmd/gosimple
$ gosimple sandbox/foo
/home/eike/gows/src/sandbox/foo/foo.go:6:2: 'if err != nil { return err }; return nil' can be simplified to 'return err' (S1013)
```

This failed in our CI with the gometalinter on the day I opened the issue and I wrote this example to reproduce it. I assume i did 'go get -u honnef.co/go/simple/cmd/gosimple' when i opened the issue.

It works with the latest version though.

**Comment by dominikh** [comment] 2017-01-20 10:26
I'll close this issue then. It's either the result of user error, an already fixed bug, or a race condition I'm already tracking and working to fix.

**Closed as completed by dominikh** 2017-01-20 10:26 UTC
